name: paperless_store_upd
description: Paperless Store
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get: ^4.6.5
  shared_preferences: ^2.2.2
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Kalpurush 
      fonts:
        - asset: assets/fonts/kalpurush.ttf